### PR TITLE
Add shell scripts: configure.sh & install.sh

### PR DESCRIPTION
**Pull request by PhilDevProg**
I added two shell scripts which make the configuration and installation process much simpler:

- configure.sh: Tells you which keys are available and writes your own key (combinations (up to 3 keys)) into src/main.js
- install.sh: Installs the needed dependencies (for Fedora, Ubuntu and Debian; if these systems aren't used, it displays a message), builds the program, installs it to the system and installs the systemd service if wanted

### CODE REVIEW

**Comment by PhilDevProg** [comment]
@qzed Btw, I think you misspelled your E-Mail adress in Cargo.toml. There's '@gmai.com' but it should be '@gmail.com', right? Just saw it so I thought maybe I should tell you.

**Comment by qzed** [comment]
> @qzed Btw, I think you misspelled your E-Mail adress in Cargo.toml. There's '@gmai.com' but it should be '@gmail.com', right? Just saw it so I thought maybe I should tell you.

Thanks for spotting that!

**Comment by qzed** [comment]
I'm not sure about the config script, this is a bit of a hack. Ideally, we should have a proper config file for that, which shouldn't be all that difficult to implement with something like `serde`/`toml`. Could you give that a try instead?

**Comment by PhilDevProg** [comment]
> I'm not sure about the config script, this is a bit of a hack.

Hmm, yeah but it's better than nothing until there's a proper solution I think.

> Ideally, we should have a proper config file for that, which shouldn't be all that difficult to implement with something like `serde`/`toml`. Could you give that a try instead?

I looked it up but I don't really understand how it works and how to implement it into the code since I don't have many experiences with Rust and how it works.

**Comment by qzed** [comment]
Okay, I've just added basic support for a config file, which is supposed to be placed at `/etc/surface-pen-button/remap.conf`. Alternatively, you can set the `SURFACE_PEN_BUTTON_CONFIG` environment variable to point to that file.

This should remove the need for the configure script, but you'll have to update the install script.

**Comment by qzed** [comment]
It would also be great if you could add an "uninstall" option for that.

**Comment by PhilDevProg** [comment]
>This should remove the need for the configure script, but you'll have to update the install script.

I'll do that later.

> It would also be great if you could add an "uninstall" option for that.

Good idea!

**Comment by PhilDevProg** [comment]
Should I make a new Pull request that only contains the install script?

**Comment by PhilDevProg** [comment]
Replaced by #6

**Pull request closed without merging**
